apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "1" 
        memory: "3Gi" 
      min:
        cpu: "200m" 
        memory: "128Mi" 
    - type: "Container"
      max:
        cpu: "1" 
        memory: "3Gi" 
      min:
        cpu: "200m" 
        memory: "128Mi" 
      default:
        cpu: "1" 
        memory: "3Gi" 
      defaultRequest:
        cpu: "500m" 
        memory: "2Gi" 
      