- src: siamaksade.openshift_sonatype_nexus
  version: 1.1.0
  name: openshift_sonatype_nexus

- src: siamaksade.openshift_gogs
  version: 1.1.0
  name: openshift_gogs

- src: siamaksade.openshift_jenkins
  version: 1.4.1
  name: openshift_jenkins
