apiVersion: v1
kind: List
items:

- kind: ImageStream
  apiVersion: 'v1'
  metadata:
    annotations:
      description: My-thai-star java image
      tags: java, mythaistar
    labels:
      app: mythaistar-java
    name: mythaistar-java

- kind: BuildConfig
  apiVersion: 'v1'
  metadata:
    labels:
      app: mythaistar-java
    name: mythaistar-java
  spec:
    
    runPolicy: 'Serial' 
    
    triggers:
    - github:
        secret: mythaistar
      type: GitHub
    - generic:
        secret: mythaistar
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
      
    source:
      contextDir: java/mtsj
      git:
        uri: https://github.com/devonfw/my-thai-star.git
        ref: develop
      type: Git
    
    strategy:
      sourceStrategy:
        env:
          - name: MAVEN_MIRROR_URL
            value: http://nexus.roadtocloudnative.svc:8081/repository/maven-public/
          - name: MAVEN_S2I_ARTIFACT_DIRS
            value: server/target
          - name: S2I_SOURCE_DEPLOYMENTS_FILTER
            value: '*.war'

        from:
          kind: ImageStreamTag
          name: 'java:8'
          namespace: openshift
      type: Source
        
    output:
      to:
        kind: ImageStreamTag
        name: 'mythaistar-java:latest'
