apiVersion: v1
kind: List
items:

- kind: ImageStream
  apiVersion: 'v1'
  metadata:
    annotations:
      description: My-thai-star angular image
      tags: javascript, mythaistar
    labels:
      app: mythaistar-angular
    name: mythaistar-angular

- kind: BuildConfig
  apiVersion: 'v1'
  metadata:
    labels:
      app: mythaistar-angular
    name: mythaistar-angular
  spec:
    
    runPolicy: 'Serial' 
    
    triggers:
    - github:
        secret: mythaistar
      type: GitHub
    - generic:
        secret: mythaistar
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
      
    source:
      contextDir: angular
      git:
        uri: https://github.com/devonfw/my-thai-star.git
        ref: develop
      type: Git
    
    strategy:
      sourceStrategy:
        env:
          - NPM_MIRROR:
            value: 'http://nexus.roadtocloudnative.svc:8081/repository/npm-group/'
            
          - name: API_ENDPOINT
            value: 'http://api-mythaistar-userXY.apps.CLUSTER_ID.openshiftworkshop.com'

        from:
          kind: ImageStreamTag
          name: 'nodejs:8'
          namespace: openshift
      type: Source
        
    output:
      to:
        kind: ImageStreamTag
        name: 'mythaistar-angular:latest'
