---
apiVersion: v1
kind: LimitRange
metadata:
  name: "core-resource-limits"
spec:
  limits:
    - default:
        cpu: 2000m
        memory: 4Gi
      defaultRequest:
        cpu: 500m
        memory: 2Gi
      max:
        memory: 6Gi
      min:
        memory: 1Mi
      type: Container
    - max:
        memory: 12Gi
      min:
        memory: 6Mi
      type: Pod

